version: '3'
services:
  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    env_file:
      - .env
      
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - streamlit