version: "3.8"

services:
  # 1) Postgres DB with pgvector
  postgres:
    image: pgvector/pgvector:0.8.0-pg15
    container_name: ${CONTAINER_NAME}
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./database/${DB_PATH}:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

  # 2) Streamlit + FAISS 앱
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    depends_on:
      - postgres
    env_file:
      - .env.prod
    ports:
      - "8501:8501"
    environment:
      STREAMLIT_SERVER_HEADLESS:         "true"
      STREAMLIT_SERVER_ENABLECORS:       "false"
      STREAMLIT_SERVER_ENABLEXSRFPROTECTION: "false"
      STREAMLIT_SERVER_ADDRESS:          "0.0.0.0"
      STREAMLIT_SERVER_PORT:             "8501"

  # 3) Nginx reverse proxy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    depends_on:
      - streamlit
    ports:
      - "80:80"
